// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'samaj_parivaar_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String ADD_MEDIA = 'assets/images/add_media.png';
  static const String ADD_POST = 'assets/images/add_post.png';
  static const String BISHI_GROUP = 'assets/images/bishi_group.png';
  static const String COMMUNITY = 'assets/images/community.png';
  static const String COMMUNITY_BLACK = 'assets/images/community_black.png';
  static const String COMMUNITY_ICON = 'assets/images/community_icon.png';
  static const String COMMUNITY_PEOPLE = 'assets/images/community_people.png';
  static const String EMAIL = 'assets/images/email.png';
  static const String ERROR_IMAGE = 'assets/images/error_image.png';
  static const String EVENT = 'assets/images/event.png';
  static const String EVENTS = 'assets/images/events.png';
  static const String GOOGLE = 'assets/images/google.png';
  static const String HOME = 'assets/images/home.png';
  static const String JOB = 'assets/images/job.png';
  static const String LOCATION = 'assets/images/location.png';
  static const String LOGO = 'assets/images/logo.png';
  static const String NAME = 'assets/images/name.png';
  static const String PASSWORD_LOCK = 'assets/images/password_lock.png';
  static const String PERSON_PROFILE = 'assets/images/person_profile.png';
  static const String POLL = 'assets/images/poll.png';
  static const String POST = 'assets/images/post.png';
  static const String REQUEST = 'assets/images/request.png';
}
