// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbK0ty85dCQ97CDYeClOq9uQt_81v1G0s',
    appId: '1:465455508425:web:417cf26e1512e93a8fd618',
    messagingSenderId: '465455508425',
    projectId: 'samaj-parivaar',
    authDomain: 'samaj-parivaar.firebaseapp.com',
    storageBucket: 'samaj-parivaar.firebasestorage.app',
    measurementId: 'G-5MKZRFHV5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuLq9YBUjPYAX3IFkx59tS3GhmrK3G6cM',
    appId: '1:465455508425:android:18344643bdd9535a8fd618',
    messagingSenderId: '465455508425',
    projectId: 'samaj-parivaar',
    storageBucket: 'samaj-parivaar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPPMSaNRAArAZxcZQs3p-eDb_lZw4LQZE',
    appId: '1:465455508425:ios:415591ecffc2d5838fd618',
    messagingSenderId: '465455508425',
    projectId: 'samaj-parivaar',
    storageBucket: 'samaj-parivaar.firebasestorage.app',
    iosBundleId: 'com.example.samajParivaarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPPMSaNRAArAZxcZQs3p-eDb_lZw4LQZE',
    appId: '1:465455508425:ios:415591ecffc2d5838fd618',
    messagingSenderId: '465455508425',
    projectId: 'samaj-parivaar',
    storageBucket: 'samaj-parivaar.firebasestorage.app',
    iosBundleId: 'com.example.samajParivaarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbK0ty85dCQ97CDYeClOq9uQt_81v1G0s',
    appId: '1:465455508425:web:0a4b1ac7ff6de5ff8fd618',
    messagingSenderId: '465455508425',
    projectId: 'samaj-parivaar',
    authDomain: 'samaj-parivaar.firebaseapp.com',
    storageBucket: 'samaj-parivaar.firebasestorage.app',
    measurementId: 'G-WER03J4EST',
  );
}
